name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: banking-app-dev
  ECS_CLUSTER: banking-app-dev-cluster
  ECS_SERVICE: banking-app-dev-service

jobs:
  trigger-codebuild:
    runs-on: codebuild-banking-app-dev-codebuild-v2-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Build and Push Docker Image
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY

          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

          cd app

          docker buildx create --use || true

          docker buildx build \
            --platform linux/amd64 \
            -t $ECR_URI:latest \
            --push .

      - name: Restart ECS Service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment \
            --region $AWS_REGION